//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum..
        /// </summary>
        internal static string Activities_content {
            get {
                return ResourceManager.GetString("Activities content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        internal static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        internal static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong captchar code.
        /// </summary>
        internal static string alertErrorCaptcha {
            get {
                return ResourceManager.GetString("alertErrorCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * All fields are mandatory.
        /// </summary>
        internal static string AllFields {
            get {
                return ResourceManager.GetString("AllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All – Inclusive service.
        /// </summary>
        internal static string All_Inclusive_service {
            get {
                return ResourceManager.GetString("All Inclusive service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rooms.
        /// </summary>
        internal static string All_rooms {
            get {
                return ResourceManager.GetString("All rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (Required).
        /// </summary>
        internal static string ArtCom {
            get {
                return ResourceManager.GetString("ArtCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Comment.
        /// </summary>
        internal static string ArticleComment {
            get {
                return ResourceManager.GetString("ArticleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles New.
        /// </summary>
        internal static string Articles_New {
            get {
                return ResourceManager.GetString("Articles New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles Related.
        /// </summary>
        internal static string Articles_Related {
            get {
                return ResourceManager.GetString("Articles Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach bar.
        /// </summary>
        internal static string Beach_bar {
            get {
                return ResourceManager.GetString("Beach bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed size.
        /// </summary>
        internal static string Bed_size {
            get {
                return ResourceManager.GetString("Bed size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        internal static string Book_Now {
            get {
                return ResourceManager.GetString("Book Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Your Travel - the most trusted WordPress booking theme.
        /// </summary>
        internal static string Book_Your_Travel___the_most_trusted_WordPress_booking_theme {
            get {
                return ResourceManager.GetString("Book Your Travel - the most trusted WordPress booking theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In enim justo, rhoncus ut, imperdiet a, venenatis vitae,
        ///                        justo. Nullam dictum felis eu pede mollis pretium. Integer
        ///                        tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean
        ///                        vulputate eleifend tellus..
        /// </summary>
        internal static string Book_Your_Travel___the_most_trusted_WordPress_booking_theme_Content {
            get {
                return ResourceManager.GetString("Book Your Travel - the most trusted WordPress booking theme Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation / Prepayment.
        /// </summary>
        internal static string Cancellation___Prepayment {
            get {
                return ResourceManager.GetString("Cancellation / Prepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donec quam felis, ultricies nec, pellentesque eu, pretium
        ///                        quis, sem. Nulla consequat massa quis enim. Donec pede justo,
        ///                        fringilla vel, aliquet nec, vulputate eget, arcu..
        /// </summary>
        internal static string Cancellation___Prepayment_content {
            get {
                return ResourceManager.GetString("Cancellation / Prepayment content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        internal static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in time.
        /// </summary>
        internal static string Check_in_time {
            get {
                return ResourceManager.GetString("Check-in time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 2 PM.
        /// </summary>
        internal static string Check_in_time_content {
            get {
                return ResourceManager.GetString("Check-in time content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out time.
        /// </summary>
        internal static string Check_out_time {
            get {
                return ResourceManager.GetString("Check-out time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until 10 AM.
        /// </summary>
        internal static string Check_out_time_content {
            get {
                return ResourceManager.GetString("Check-out time content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children and extra beds.
        /// </summary>
        internal static string Children_and_extra_beds {
            get {
                return ResourceManager.GetString("Children and extra beds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In enim justo, rhoncus ut, imperdiet a, venenatis vitae,
        ///                        justo. Nullam dictum felis eu pede mollis pretium..
        /// </summary>
        internal static string Children_and_extra_beds_content {
            get {
                return ResourceManager.GetString("Children and extra beds content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with us.
        /// </summary>
        internal static string Connect_with_us {
            get {
                return ResourceManager.GetString("Connect with us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenient.
        /// </summary>
        internal static string Convenient {
            get {
                return ResourceManager.GetString("Convenient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like what you see? Are you ready to stand out?.
        /// </summary>
        internal static string Do_you_like_what_you_see__Are_you_ready_to_stand_out_ {
            get {
                return ResourceManager.GetString("Do you like what you see? Are you ready to stand out?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address *.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string EnterEmailNews {
            get {
                return ResourceManager.GetString("EnterEmailNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Keywords.
        /// </summary>
        internal static string EnterKey {
            get {
                return ResourceManager.GetString("EnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your message *.
        /// </summary>
        internal static string EnterMessage {
            get {
                return ResourceManager.GetString("EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name *.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Comment.
        /// </summary>
        internal static string EnterRevComment {
            get {
                return ResourceManager.GetString("EnterRevComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your E-mail.
        /// </summary>
        internal static string EnterRevEmail {
            get {
                return ResourceManager.GetString("EnterRevEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Full Name.
        /// </summary>
        internal static string EnterRevName {
            get {
                return ResourceManager.GetString("EnterRevName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENTS.
        /// </summary>
        internal static string EVENTS {
            get {
                return ResourceManager.GetString("EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience the finest luxury in privacy &amp; tranquility.
        /// </summary>
        internal static string Experience_the_finest_luxury_in_privacy___tranquility {
            get {
                return ResourceManager.GetString("Experience the finest luxury in privacy & tranquility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In enim justo, rhoncus ut, imperdiet a, venenatis vitae,
        ///                        justo. Nullam dictum felis eu pede mollis pretium. Integer
        ///                        tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean
        ///                        vulputate eleifend tellus..
        /// </summary>
        internal static string Experience_the_finest_luxury_in_privacy___tranquility_Content {
            get {
                return ResourceManager.GetString("Experience the finest luxury in privacy & tranquility Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air conditioning.
        /// </summary>
        internal static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach.
        /// </summary>
        internal static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free WiFi.
        /// </summary>
        internal static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport shuttle.
        /// </summary>
        internal static string F4 {
            get {
                return ResourceManager.GetString("F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free parking.
        /// </summary>
        internal static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimming pool.
        /// </summary>
        internal static string F6 {
            get {
                return ResourceManager.GetString("F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        internal static string Facilities {
            get {
                return ResourceManager.GetString("Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine dining.
        /// </summary>
        internal static string Fine_dining {
            get {
                return ResourceManager.GetString("Fine dining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        internal static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record your most impressive moments at Nam Cuong Nam Dinh Hotel.
        /// </summary>
        internal static string Gallery_content {
            get {
                return ResourceManager.GetString("Gallery content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET IN TOUCH.
        /// </summary>
        internal static string GetInTouch {
            get {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET STARTED NOW.
        /// </summary>
        internal static string GET_STARTED_NOW {
            get {
                return ResourceManager.GetString("GET STARTED NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET YOUR LICENSE.
        /// </summary>
        internal static string GET_YOUR_LICENSE {
            get {
                return ResourceManager.GetString("GET YOUR LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hightlights.
        /// </summary>
        internal static string Hightlight {
            get {
                return ResourceManager.GetString("Hightlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions don&apos;t hesistate to contact us..
        /// </summary>
        internal static string IfYouQuestion {
            get {
                return ResourceManager.GetString("IfYouQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I read and agree with the  &lt;a href=&quot;javascript:void(0)&quot; onclick=&quot;ShowCondition()&quot;&gt;terms &amp; conditions &lt;/a&gt; of the .
        /// </summary>
        internal static string Igree {
            get {
                return ResourceManager.GetString("Igree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info at bookyourtravel.
        /// </summary>
        internal static string info_at_bookyourtravel {
            get {
                return ResourceManager.GetString("info at bookyourtravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor..
        /// </summary>
        internal static string Internet_content {
            get {
                return ResourceManager.GetString("Internet content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a comment.
        /// </summary>
        internal static string LeaveComment {
            get {
                return ResourceManager.GetString("LeaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEAVE A REVIEW.
        /// </summary>
        internal static string LeaveReview {
            get {
                return ResourceManager.GetString("LeaveReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxury accommodation.
        /// </summary>
        internal static string Luxury_accommodation {
            get {
                return ResourceManager.GetString("Luxury accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxury rooms.
        /// </summary>
        internal static string Luxury_rooms {
            get {
                return ResourceManager.GetString("Luxury rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum &amp; People.
        /// </summary>
        internal static string MaxPeople {
            get {
                return ResourceManager.GetString("MaxPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messeger.
        /// </summary>
        internal static string Messeger {
            get {
                return ResourceManager.GetString("Messeger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE INFO.
        /// </summary>
        internal static string MORE_INFO {
            get {
                return ResourceManager.GetString("MORE INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        internal static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not comment!.
        /// </summary>
        internal static string NotComment {
            get {
                return ResourceManager.GetString("NotComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments on the web site reflect the
        ///                            views of their authors, and not necessarily the views of the
        ///                            bookyourtravel internet portal. Requested to refrain from
        ///                            insults, swearing and vulgar expression. We reserve the
        ///                            right to delete any comment without notice explanations..
        /// </summary>
        internal static string Note_Content {
            get {
                return ResourceManager.GetString("Note Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address will not be published. Required fields
        ///                            are signed with.
        /// </summary>
        internal static string notPublishEmail {
            get {
                return ResourceManager.GetString("notPublishEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not find result!.
        /// </summary>
        internal static string NotResult {
            get {
                return ResourceManager.GetString("NotResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not review!.
        /// </summary>
        internal static string NotReview {
            get {
                return ResourceManager.GetString("NotReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or contact us directly.
        /// </summary>
        internal static string Or_contact_us_directly {
            get {
                return ResourceManager.GetString("Or contact us directly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Awards.
        /// </summary>
        internal static string Our_Awards {
            get {
                return ResourceManager.GetString("Our Awards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        internal static string Parking {
            get {
                return ResourceManager.GetString("Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus..
        /// </summary>
        internal static string Parking_content {
            get {
                return ResourceManager.GetString("Parking content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Night.
        /// </summary>
        internal static string Per_Night {
            get {
                return ResourceManager.GetString("Per Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer tincidunt. Cras dapibus. Vivamus elementum semper
        ///                        nisi. Aenean vulputate eleifend tellus..
        /// </summary>
        internal static string Pets_content {
            get {
                return ResourceManager.GetString("Pets content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies to.
        /// </summary>
        internal static string Replies_to {
            get {
                return ResourceManager.GetString("Replies to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment  (Required).
        /// </summary>
        internal static string RevComment {
            get {
                return ResourceManager.GetString("RevComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  (Required).
        /// </summary>
        internal static string RevEmail {
            get {
                return ResourceManager.GetString("RevEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Required).
        /// </summary>
        internal static string RevName {
            get {
                return ResourceManager.GetString("RevName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Description.
        /// </summary>
        internal static string RoomDesc {
            get {
                return ResourceManager.GetString("RoomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Features.
        /// </summary>
        internal static string RoomFeature {
            get {
                return ResourceManager.GetString("RoomFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
        ///                        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis
        ///                        natoque penatibus et magnis dis parturient montes, nascetur
        ///                        ridiculus mus..
        /// </summary>
        internal static string Room_content {
            get {
                return ResourceManager.GetString("Room content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room other.
        /// </summary>
        internal static string Room_other {
            get {
                return ResourceManager.GetString("Room other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room size.
        /// </summary>
        internal static string Room_size {
            get {
                return ResourceManager.GetString("Room size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        internal static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select dates.
        /// </summary>
        internal static string Select_date {
            get {
                return ResourceManager.GetString("Select date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT YOUR ROOM.
        /// </summary>
        internal static string SELECT_YOUR_ROOM {
            get {
                return ResourceManager.GetString("SELECT YOUR ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND MESSAGE.
        /// </summary>
        internal static string SendCom {
            get {
                return ResourceManager.GetString("SendCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Comment.
        /// </summary>
        internal static string SendComment {
            get {
                return ResourceManager.GetString("SendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND MESSAGE.
        /// </summary>
        internal static string SENDMESSAGE {
            get {
                return ResourceManager.GetString("SENDMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND INQUIRI.
        /// </summary>
        internal static string SEND_INQUIRI {
            get {
                return ResourceManager.GetString("SEND INQUIRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW MORE.
        /// </summary>
        internal static string SHOW_MORE {
            get {
                return ResourceManager.GetString("SHOW MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Room.
        /// </summary>
        internal static string Special_Room {
            get {
                return ResourceManager.GetString("Special Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to our email newsletter to receive updates and news..
        /// </summary>
        internal static string SubscibeToEmail {
            get {
                return ResourceManager.GetString("SubscibeToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe Our Newsletter.
        /// </summary>
        internal static string SubscribeOurNewsletter {
            get {
                return ResourceManager.GetString("SubscribeOurNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities us.
        /// </summary>
        internal static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities other.
        /// </summary>
        internal static string Utilities_other {
            get {
                return ResourceManager.GetString("Utilities other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW RATES FOR ALL ROOMS HERE.
        /// </summary>
        internal static string VIEWRATES {
            get {
                return ResourceManager.GetString("VIEWRATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW ALL.
        /// </summary>
        internal static string VIEW_ALL {
            get {
                return ResourceManager.GetString("VIEW ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far far away, behind the word mountains, far from the
        ///                        countries Vokalia and Consonantia, there live the blind texts..
        /// </summary>
        internal static string WC1 {
            get {
                return ResourceManager.GetString("WC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far far away, behind the word mountains, far from the
        ///                        countries Vokalia and Consonantia, there live the blind texts..
        /// </summary>
        internal static string WC2 {
            get {
                return ResourceManager.GetString("WC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far far away, behind the word mountains, far from the
        ///                        countries Vokalia and Consonantia, there live the blind texts..
        /// </summary>
        internal static string WC3 {
            get {
                return ResourceManager.GetString("WC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far far away, behind the word mountains, far from the
        ///                        countries Vokalia and Consonantia, there live the blind texts..
        /// </summary>
        internal static string WC4 {
            get {
                return ResourceManager.GetString("WC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World - class dining.
        /// </summary>
        internal static string World_class_dining {
            get {
                return ResourceManager.GetString("World class dining", resourceCulture);
            }
        }
    }
}
